/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/SidebarView copy.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IBiBarChartLine: typeof import('~icons/bi/bar-chart-line')['default']
    IBiBarChartLineFill: typeof import('~icons/bi/bar-chart-line-fill')['default']
    IBiCalendar2Date: typeof import('~icons/bi/calendar2-date')['default']
    IBiChart: typeof import('~icons/bi/chart')['default']
    IBiChartline: typeof import('~icons/bi/chartline')['default']
    IBiChartLine: typeof import('~icons/bi/chart-line')['default']
    IBiChartLineFill: typeof import('~icons/bi/chart-line-fill')['default']
    IBiHome: typeof import('~icons/bi/home')['default']
    IBiHouse: typeof import('~icons/bi/house')['default']
    IBiPlayCircle: typeof import('~icons/bi/play-circle')['default']
    IBiPlayCircleFill: typeof import('~icons/bi/play-circle-fill')['default']
    IBiRobot: typeof import('~icons/bi/robot')['default']
    IBiSpeedometer2: typeof import('~icons/bi/speedometer2')['default']
    MainView: typeof import('./src/components/MainView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarView: typeof import('./src/components/SidebarView.vue')['default']
  }
}
